# Site settings
title: diogorusso
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
description: diogorusso
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# INDEX Pagination
paginate:    5
paginate_path: /page:num
